version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    env_file:
      - ./server/.env
    environment:
      MYSQL_ROOT_HOST: '%'      
    volumes:
      - ~/mysql:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 2s
        retries: 10
    networks:
      - mynetwork

  be:
    build: ./server
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./server/.env
    restart: always
    networks:
      - mynetwork

  fe:
    build: ./client
    ports:
      - "3000:3000"
    restart: always
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    depends_on:
      - mysql
    networks:
      - mynetwork

volumes:
  mysql:
    name: db

networks:
  mynetwork: