version: "3.8"

services:
  fe:
    build: ./client
    ports:
      - "3000:3000"
    restart: always

  mysql:
    container_name: localhost
    image: mysql:latest
    restart: always
    ports:
      - 3307:3306
    env_file:
      - ./server/.env
    volumes:
      - mysql:/var/lib/mysql

  be:
    build: ./server
    ports:
      - 8080:80
    depends_on:
      - mysql
    env_file:
      - ./server/.env

volumes:
  mysql:
    name: db
